# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.29.1"
neorg = { version = "8.5.0", opt = true }
nvim-metals = { version = "0.9.x", opt = true }
"telescope.nvim" = "scm"
nvim-web-devicons = "0.100"
luasnip = { version = "2.3.0", opt = true }
"fidget.nvim" = "1.4.1"
"dressing.nvim" = "2.2.1"
nvim-jdtls = { version = "0.2.0", opt = true }
nvim-dap-ui = { version = "4.0.0", opt = true }
nvim-dap-go = { version = "scm", opt = true }
neotest = { version = "5.2.5", opt = true }
"flatten.nvim" = "0.5.1"
"venn.nvim" = "scm"
"hydra.nvim" = "1.0.2"
