#!/bin/bash
# vim: set ft=sh

[[ $1 == "run" ]] || (sleep 1 && echo "compilation failure!" >&2 && exit 1) || exit 1

file=$([ -n "$2" ] && basename "$2" || echo "file.c")

for i in pre-processing... compiling... assembling... linking... done!; do
	sleep 1
	echo "$file: $i"
done
